// Word lists for anonymous aliases like "Зелёный Кролик" or "Green Rabbit".
// Russian adjectives agree with the animal's grammatical gender, so they come in two forms.

export interface RuAdjective {
  masculine: string;
  feminine: string;
}

export const ruAdjectives: readonly RuAdjective[] = [
  { masculine: 'Зелёный', feminine: 'Зелёная' },
  { masculine: 'Рыжий', feminine: 'Рыжая' },
  { masculine: 'Синий', feminine: 'Синяя' },
  { masculine: 'Жёлтый', feminine: 'Жёлтая' },
  { masculine: 'Серебряный', feminine: 'Серебряная' },
  { masculine: 'Золотой', feminine: 'Золотая' },
  { masculine: 'Быстрый', feminine: 'Быстрая' },
  { masculine: 'Тихий', feminine: 'Тихая' },
  { masculine: 'Храбрый', feminine: 'Храбрая' },
  { masculine: 'Спокойный', feminine: 'Спокойная' },
  { masculine: 'Хитрый', feminine: 'Хитрая' },
  { masculine: 'Весёлый', feminine: 'Весёлая' },
  { masculine: 'Любопытный', feminine: 'Любопытная' },
  { masculine: 'Добрый', feminine: 'Добрая' },
  { masculine: 'Удачливый', feminine: 'Удачливая' },
  { masculine: 'Сонный', feminine: 'Сонная' },
  { masculine: 'Солнечный', feminine: 'Солнечная' },
  { masculine: 'Мудрый', feminine: 'Мудрая' },
  { masculine: 'Дикий', feminine: 'Дикая' },
  { masculine: 'Застенчивый', feminine: 'Застенчивая' },
  { masculine: 'Гордый', feminine: 'Гордая' },
  { masculine: 'Задумчивый', feminine: 'Задумчивая' },
  { masculine: 'Бодрый', feminine: 'Бодрая' },
  { masculine: 'Пушистый', feminine: 'Пушистая' },
  { masculine: 'Уютный', feminine: 'Уютная' },
  { masculine: 'Смелый', feminine: 'Смелая' },
  { masculine: 'Ловкий', feminine: 'Ловкая' },
  { masculine: 'Лесной', feminine: 'Лесная' },
  { masculine: 'Полярный', feminine: 'Полярная' },
  { masculine: 'Утренний', feminine: 'Утренняя' },
];

export const ruMasculineAnimals: readonly string[] = [
  'Кролик',
  'Ёж',
  'Волк',
  'Медведь',
  'Енот',
  'Барсук',
  'Сокол',
  'Тюлень',
  'Бобр',
  'Олень',
  'Заяц',
  'Журавль',
  'Пингвин',
  'Воробей',
  'Лось',
  'Хомяк',
  'Филин',
  'Крот',
  'Бурундук',
  'Ворон',
];

export const ruFeminineAnimals: readonly string[] = [
  'Лиса',
  'Белка',
  'Сова',
  'Выдра',
  'Чайка',
  'Рысь',
  'Панда',
  'Цапля',
  'Косуля',
  'Ласточка',
  'Синица',
  'Ящерица',
  'Утка',
  'Мышь',
  'Зебра',
];

export const enAdjectives: readonly string[] = [
  'Green',
  'Red',
  'Blue',
  'Yellow',
  'Silver',
  'Golden',
  'Swift',
  'Quiet',
  'Brave',
  'Calm',
  'Clever',
  'Cheerful',
  'Curious',
  'Gentle',
  'Lucky',
  'Sleepy',
  'Sunny',
  'Wise',
  'Wild',
  'Shy',
  'Proud',
  'Thoughtful',
  'Lively',
  'Fluffy',
  'Cozy',
  'Bold',
  'Nimble',
  'Forest',
  'Polar',
  'Morning',
];

export const enAnimals: readonly string[] = [
  'Rabbit',
  'Hedgehog',
  'Wolf',
  'Bear',
  'Raccoon',
  'Badger',
  'Falcon',
  'Seal',
  'Beaver',
  'Deer',
  'Hare',
  'Crane',
  'Penguin',
  'Sparrow',
  'Moose',
  'Hamster',
  'Owl',
  'Mole',
  'Chipmunk',
  'Raven',
  'Fox',
  'Squirrel',
  'Otter',
  'Seagull',
  'Lynx',
  'Panda',
  'Heron',
  'Swallow',
  'Lizard',
  'Duck',
];
