/**
 * Interface texts. The back office is for the team, not for users, so it has one language
 * (the user-facing catalogue with `ru` and `en` is in `packages/shared/src/texts`).
 */
export const texts = {
  appName: 'human-msg · бэкофис',
  login: {
    title: 'Вход в бэкофис',
    login: 'Логин',
    password: 'Пароль',
    submit: 'Войти',
    required: 'Обязательное поле',
    failed: 'Вход не выполнен',
  },
  channels: { web: 'Веб', telegram: 'Telegram' },
  yes: 'да',
  no: 'нет',
  any: 'Все',
  users: {
    menu: 'Пользователи',
    title: 'Пользователи',
    alias: 'Псевдоним',
    channel: 'Канал',
    locale: 'Язык',
    kind: 'Тип',
    live: 'Живой',
    test: 'Тестовый',
    staff: 'Служебный',
    receiving: 'Получает вопросы',
    receivingOff: 'не беспокоить',
    botBlocked: 'бот заблокирован',
    asked: 'Вопросов',
    answered: 'Ответов',
    lastSeen: 'Был в сети',
    createdAt: 'Регистрация',
    createdRange: 'Дата регистрации',
    search: 'Поиск по псевдониму',
    find: 'Найти',
    reset: 'Сбросить',
    open: 'Открыть',
    card: 'Пользователь',
    telegramId: 'Telegram id',
    cooldownUntil: 'Пауза до',
    missedDeadlines: 'Пропущено дедлайнов подряд',
    id: 'id',
  },
  history: {
    title: 'Переписка',
    empty: 'Пользователь ещё ничего не спрашивал и не отвечал',
    more: 'Показать ещё',
    allQuestions: 'Все вопросы пользователя с назначениями',
    asked: 'Спросил(а)',
    answeredTo: 'Ответил(а) на вопрос',
    questionOf: 'Вопрос от',
    answerFrom: 'Ответ от',
    noAnswer: 'Ответа нет',
  },
  questions: {
    menu: 'Вопросы',
    title: 'Вопросы',
    all: 'Все',
    createdAt: 'Задан',
    status: 'Статус',
    author: 'Автор',
    text: 'Вопрос',
    receivers: 'Получателей',
    answer: 'Ответ',
    answerFrom: 'Ответ от',
    noAnswer: 'Ответа нет',
    expiresAt: 'Истекает',
    answeredAt: 'Отвечен',
    assignments: 'Назначения',
    noAssignments: 'Вопрос ещё никому не назначался',
    receiver: 'Получатель',
    assignedAt: 'Назначен',
    deadlineAt: 'Дедлайн',
    endedAt: 'Завершено',
    outcome: 'Итог',
    authorFilter: 'Вопросы автора',
  },
  expired: {
    menu: 'Без ответа',
    title: 'Вопросы без ответа',
    hint: 'Никто не успел ответить на эти вопросы. Ответ отсюда придёт автору как обычный ответ от случайного псевдонима, без пометки команды.',
    empty: 'Все вопросы получили ответ',
    expiredAt: 'Истёк',
    answer: 'Ответить',
    modalTitle: 'Ответ автору',
    question: 'Вопрос',
    yourAnswer: 'Ответ',
    send: 'Отправить ответ',
    cancel: 'Отмена',
    sent: 'Ответ отправлен автору',
  },
  messageErrors: {
    empty: 'Напишите ответ',
    tooShort: 'Ответ слишком короткий',
    tooLong: 'Ответ слишком длинный',
  },
  testUsers: {
    menu: 'Тестовые пользователи',
    title: 'Тестовые пользователи',
    hint: 'Тестовые пользователи живут в отдельном пуле: их вопросы получают только другие тестовые пользователи, получатель выбирается по обычным правилам. Сообщение тестового пользователя, у которого есть назначенный вопрос, — это ответ на него.',
    create: 'Создать',
    locale: 'Язык нового пользователя',
    created: 'Создан тестовый пользователь',
    empty: 'Тестовых пользователей пока нет',
    available: 'Доступен',
    availableHint: 'Получает вопросы, как веб-пользователь с открытой страницей',
    incoming: 'Вопрос от',
    deadline: 'дедлайн',
    pending: 'Свой вопрос',
    idle: 'Нет ни назначенного вопроса, ни своего вопроса без ответа',
    cooldown: 'Пауза до',
    message: 'Сообщение',
    ask: 'Спросить',
    answer: 'Ответить',
    skip: 'Пропустить',
    asked: 'Вопрос задан',
    askedQueued: 'Вопрос в очереди: свободного получателя нет',
    answered: 'Ответ отправлен',
    skipped: 'Вопрос пропущен',
    conversation: 'Переписка',
  },
  settings: {
    menu: 'Настройки',
    title: 'Настройки',
    hint: 'Изменения действуют сразу, без перезапуска, но только для новых вопросов, назначений и пауз: у уже созданных сроки зафиксированы.',
    groups: {
      time: 'Сроки',
      cooldowns: 'Паузы',
      telegram: 'Telegram',
      limits: 'Лимиты',
    },
    minutes: 'мин',
    default: 'По умолчанию',
    useDefault: 'вернуть',
    save: 'Сохранить',
    saved: 'Настройки сохранены',
    nothingChanged: 'Ничего не изменено',
    reset: 'Отменить изменения',
    fields: {
      QUESTION_TTL: [
        'Время жизни вопроса',
        'Сколько вопрос может ждать ответа, прежде чем станет «без ответа»',
      ],
      ANSWER_TIMEOUT: ['Время на ответ', 'Сколько времени у одного получателя на ответ'],
      ANSWER_REMINDER: ['Напоминание', 'За сколько до дедлайна напомнить получателю'],
      COOLDOWN_TELEGRAM: ['После ответа (Telegram)', 'Пауза после ответа в Telegram'],
      COOLDOWN_WEB: ['После ответа (веб)', 'Пауза после ответа в вебе'],
      COOLDOWN_SKIP: [
        'После пропуска',
        'Пауза после «пропустить» или пропущенного дедлайна, оба канала',
      ],
      QUIET_HOURS: [
        'Тихие часы',
        'ЧЧ:ММ-ЧЧ:ММ, сообщения бота приходят без звука; одинаковые начало и конец выключают',
      ],
      QUIET_HOURS_TZ: ['Часовой пояс тихих часов', 'Например, Europe/Moscow'],
      AUTO_DND_AFTER_MISSED: [
        'Автоматический «не беспокоить»',
        'После скольких пропущенных дедлайнов подряд; 0 — выключено',
      ],
      QUESTIONS_PER_DAY: [
        'Вопросов в сутки',
        'Лимит вопросов одного пользователя за скользящие 24 часа',
      ],
      MESSAGE_MAX_LENGTH: ['Длина сообщения', 'Максимум символов в вопросе и ответе'],
    },
    invalid: {
      reminder: 'Напоминание должно быть раньше дедлайна: меньше времени на ответ',
      quietHours: 'Формат ЧЧ:ММ-ЧЧ:ММ, например 23:00-09:00',
      timeZone: 'Неизвестный часовой пояс',
      number: 'Недопустимое значение',
    },
  },
  outcome: {
    active: 'ждёт ответа',
    answered: 'ответил(а)',
    timed_out: 'не успел(а)',
    skipped: 'пропустил(а)',
    reported: 'пожаловался(ась)',
    undeliverable: 'не доставлено',
  },
  questionStatus: {
    queued: 'в очереди',
    assigned: 'назначен',
    answered: 'отвечен',
    expired: 'без ответа',
  },
  errors: {
    invalid_credentials: 'Неверный логин или пароль',
    too_many_attempts: 'Слишком много попыток входа, попробуйте позже',
    backoffice_disabled: 'Бэкофис не настроен на сервере',
    invalid_request: 'Некорректный запрос',
    not_found: 'Не найдено',
    not_expired: 'На этот вопрос уже ответили',
    invalid: 'Недопустимые значения настроек',
    unknown_key: 'Неизвестная настройка',
    not_test_user: 'Это не тестовый пользователь',
    no_active_assignment: 'Назначенного вопроса уже нет',
    awaitingAnswer: 'Пользователь ждёт ответа на свой вопрос: новый задать нельзя',
    dailyLimit: 'Исчерпан дневной лимит вопросов',
    empty: 'Пустой текст',
    tooShort: 'Текст слишком короткий',
    tooLong: 'Текст слишком длинный',
    unauthorized: 'Требуется вход',
    network: 'Не удалось связаться с сервером',
    unknown: 'Что-то пошло не так',
  },
} as const;

/** Text for a reason code the server sent; unknown codes get the generic message. */
export const errorText = (code: string): string =>
  (texts.errors as Record<string, string>)[code] ?? texts.errors.unknown;
